TabToggles:CreateSection("Toggles")
TabToggles:CreateToggle({Name="Player ESP",CurrentValue=false,Flag="PlayerESP",Callback=togglePlayerESP})
TabToggles:CreateToggle({Name="Full Bright",CurrentValue=false,Flag="FullBright",Callback=toggleFullBright})
TabToggles:CreateToggle({Name="No-Clip",CurrentValue=false,Flag="NoClip",Callback=toggleNoClip})
TabToggles:CreateToggle({Name="Infinite Jump",CurrentValue=false,Flag="InfiniteJump",Callback=toggleInfiniteJump})
TabESP:CreateSection("ESP Settings")
TabESP:CreateToggle({Name="Enable ESP",CurrentValue=false,Flag="ESPEnabled",Callback=togglePlayerESP})
TabESP:CreateSlider({Name="Max ESP Distance",Range={50,9999},Increment=50,Suffix=" studs",CurrentValue=1000,Flag="ESPMaxDist",Callback=function(v) ESPSettings.MaxDistance=v end})
TabESP:CreateSection("Info")
TabESP:CreateLabel("Set to 9999 for unlimited range.")
TabLockOn:CreateSection("Lock-On")
TabLockOn:CreateToggle({Name="Enable Lock-On",CurrentValue=false,Flag="LockOnEnabled",Callback=toggleLockOn})
TabLockOn:CreateToggle({Name="Team Check (Enemies Only)",CurrentValue=false,Flag="LockOnTeamCheck",Callback=function(v) LockOnSettings.TeamCheck=v end})
TabLockOn:CreateToggle({Name="Sticky Target",CurrentValue=true,Flag="LockOnSticky",Callback=function(v) LockOnSettings.StickyTarget=v end})
TabLockOn:CreateToggle({Name="Instant Snap",CurrentValue=false,Flag="LockOnInstant",Callback=function(v) LockOnSettings.InstantSnap=v end})
TabLockOn:CreateToggle({Name="Velocity Prediction",CurrentValue=true,Flag="LockOnPrediction",Callback=function(v) LockOnSettings.Prediction=v end})
TabLockOn:CreateSection("Bullet Compensation")
TabLockOn:CreateToggle({Name="Bullet Velocity Compensation",CurrentValue=true,Flag="BulletVelocity",Callback=function(v) LockOnSettings.BulletVelocity=v end})
TabLockOn:CreateToggle({Name="Gravity Drop Compensation",CurrentValue=true,Flag="GravityComp",Callback=function(v) LockOnSettings.GravityComp=v end})
TabLockOn:CreateSlider({Name="Bullet Speed",Range={100,5000},Increment=50,Suffix=" st/s",CurrentValue=500,Flag="BulletSpeed",Callback=function(v) LockOnSettings.BulletSpeed=v end})
TabLockOn:CreateSlider({Name="Gravity Strength",Range={50,400},Increment=10,Suffix="",CurrentValue=196,Flag="GravityStrength",Callback=function(v) LockOnSettings.Gravity=v end})
TabLockOn:CreateSection("Adjustment")
TabLockOn:CreateSlider({Name="Smoothness (higher = snappier)",Range={1,100},Increment=1,Suffix="",CurrentValue=50,Flag="LockOnSmoothness",Callback=function(v) LockOnSettings.Smoothness=v/100 end})
TabLockOn:CreateSlider({Name="Screen FOV Radius",Range={50,500},Increment=10,Suffix="px",CurrentValue=150,Flag="LockOnFOV",Callback=function(v) LockOnSettings.FOVRadius=v refreshFOV() end})
TabLockOn:CreateSlider({Name="Max Lock Distance",Range={50,2000},Increment=50,Suffix=" st",CurrentValue=500,Flag="LockOnMaxDist",Callback=function(v) LockOnSettings.MaxDistance=v end})
TabLockOn:CreateDropdown({Name="Aim Part",Options={"Head","HumanoidRootPart","UpperTorso","LowerTorso"},CurrentOption={"Head"},Flag="LockOnAimPart",Callback=function(v) LockOnSettings.AimPart=v[1] end})
TabPlayer:CreateSection("Player Mods")
TabPlayer:CreateButton({Name="Infinite Yield",Callback=function() exec("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source") end})
TabPlayer:CreateButton({Name="Fly",Callback=function() exec("https://arceus-x-neo.github.io/fly/") end})
TabPlayer:CreateButton({Name="Speed Hub X",Callback=function() exec("https://raw.githubusercontent.com/AhmadV99/Speed-Hub-X/main/Speed%20Hub%20X.lua") end})
TabPlayer:CreateButton({Name="Walkspeed",Callback=function() exec("https://raw.githubusercontent.com/Biasaemail/SCRIPT-ROBLOX-LUA-ME/refs/heads/main/WALKSPEED") end})
TabWorld:CreateSection("World & Server")
TabWorld:CreateButton({Name="Black Hole Troll",Callback=function() exec("https://raw.githubusercontent.com/Bac0nHck/Scripts/main/BringFlingPlayers") end})
TabWorld:CreateButton({Name="Fling",Callback=function() exec("https://raw.githubusercontent.com/Biasaemail/FOR-TESTING-SCRIPT/refs/heads/main/TEST%20FLING%20LOL.txt") end})
TabWorld:CreateButton({Name="Teleport",Callback=function() exec("https://raw.githubusercontent.com/Biasaemail/MY-SCRIPT-LUA-ROBLOX/refs/heads/main/TELEPROT%20J.929283938") end})
TabWorld:CreateButton({Name="Sigma Spy",Callback=function() exec("https://raw.githubusercontent.com/depthso/Sigma-Spy/refs/heads/main/Main.lua") end})
TabTools:CreateSection("Tools & Items")
TabTools:CreateButton({Name="Copy Tools",Callback=function() exec("https://raw.githubusercontent.com/Biasaemail/SCRIPT-ROBLOX-LUA-ME/refs/heads/main/COPY%20TOOLS%20V.1") end})
TabTools:CreateButton({Name="Delete Tools",Callback=function() exec("https://raw.githubusercontent.com/Biasaemail/SCRIPT-ROBLOX-LUA-ME/refs/heads/main/Detele%20Tools") end})
TabTools:CreateButton({Name="Fly Car",Callback=function() exec("https://raw.githubusercontent.com/Biasaemail/SCRIPT-ROBLOX-LUA-ME/refs/heads/main/FLY%20CAR") end})
TabTools:CreateButton({Name="ANTI BL LT2",Callback=function() exec("https://raw.githubusercontent.com/Biasaemail/SCRIPT-ROBLOX-LUA-ME/refs/heads/main/ANTI%20BL%20LT2") end})
TabHubs:CreateSection("Game Hubs")
TabHubs:CreateButton({Name="Xhub MM2",Callback=function() exec("https://raw.githubusercontent.com/Au0yX/Community/main/XhubMM2") end})
TabHubs:CreateButton({Name="No Lag HUB",Callback=function() exec("https://raw.githubusercontent.com/NoLag-id/No-Lag-HUB/refs/heads/main/Loader/LoaderV1.lua") end})
Rayfield:LoadConfiguration()
print("Nova Part 2 Loaded")
